In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Import necessary libraries
import pandas as pd

# Path to your CSV file in Google Drive
file_path_AccidentReports = "/content/drive/My Drive/accident_data.csv"

Mounted at /content/drive


In [ ]:
X = pd.read_csv(file_path_AccidentReports)

In [ ]:
file_path_AccidentReports2 = "/content/drive/My Drive/output.csv"
X2 = pd.read_csv(file_path_AccidentReports2)

In [ ]:
X1 = X

In [ ]:
X = X.drop(['Collision_TypeB', 'InjuryType', 'Hit_Run', 'Landmark_first', 'Accident_Road', 'landmark_second', 'Distance_LandMark_First', 'Distance_LandMark_Second', 'Surface_Type', 'Accident_Description', 'Injury_Nature', 'Crime_No', 'RI', 'Noofvehicle_involved', 'Accident_Classification', 'Accident_Location', 'Accident_SpotB', 'Main_Cause', 'Collision_Type', 'Junction_Control', 'Road_Condition', 'Lane_Type', 'Road_Markings', 'Spot_Conditions', 'Side_Walk', 'RoadJunction'], axis = 1)

In [ ]:
X.isnull().sum()


DISTRICTNAME                0
UNITNAME                    0
Year                        0
Accident_Spot               0
Accident_SubLocation        0
Severity                    0
Road_Character              0
Road_Type                   0
Surface_Condition           0
Weather                     0
Latitude                    0
Longitude                   0
Month                   20959
age                     20959
Sex                     21007
PersonType              20959
dtype: int64

In [ ]:

X.nunique()


DISTRICTNAME             38
UNITNAME                727
Year                      8
Accident_Spot            20
Accident_SubLocation     15
Severity                 11
Road_Character           13
Road_Type                18
Surface_Condition         7
Weather                  17
Latitude                 54
Longitude                55
Month                    12
age                     106
Sex                       3
PersonType               10
dtype: int64

In [ ]:
X_Dataset = X

In [ ]:
accidentdata = X

In [ ]:
accidentdata = accidentdata.drop('Surface_Condition', axis = 1)

In [ ]:
X_Dataset2 = accidentdata

In [ ]:
accidentdata = accidentdata.drop(['PersonType', 'Sex', 'Weather'], axis = 1)

In [ ]:
accidentdata

DISTRICTNAME                        UNITNAME  Year Accident_Spot  \
0          Bagalkot          Amingad Police Station  2016    Bottleneck   
1          Bagalkot          Amingad Police Station  2016    Bottleneck   
2          Bagalkot          Amingad Police Station  2016        Bridge   
3          Bagalkot          Amingad Police Station  2016        Bridge   
4          Bagalkot          Amingad Police Station  2016        Bridge   
...             ...                             ...   ...           ...   
487829       Yadgir  Yadgiri Traffic Police Station  2023   Cross roads   
487830       Yadgir  Yadgiri Traffic Police Station  2023   Cross roads   
487831       Yadgir  Yadgiri Traffic Police Station  2023         Other   
487832       Yadgir  Yadgiri Traffic Police Station  2023   Cross roads   
487833       Yadgir  Yadgiri Traffic Police Station  2023        Curves   

                  Accident_SubLocation         Severity     Road_Character  \
0                            Open area  Grievous Injury              Curve   
1                            Open area  Grievous Injury              Curve   
2            Narrow bridge or culverts            Fatal  Straight and flat   
3            Narrow bridge or culverts            Fatal              Curve   
4            Narrow bridge or culverts            Fatal              Curve   
...                                ...              ...                ...   
487829             Near office complex  Grievous Injury              Curve   
487830             Near office complex  Grievous Injury              Curve   
487831  Near a factory industrial area            Fatal  Straight and flat   
487832                Residential area  Grievous Injury              Curve   
487833                Residential area  Grievous Injury  Straight and flat   

                  Road_Type  Month  
0             State Highway    8.0  
1             State Highway    8.0  
2             State Highway    8.0  
3             State Highway    8.0  
4             State Highway    8.0  
...                     ...    ...  
487829  Minor District Road    5.0  
487830  Minor District Road    5.0  
487831     National Highway    7.0  
487832     National Highway    8.0  
487833     National Highway    3.0  

[487834 rows x 9 columns]

In [ ]:
accidentdata = accidentdata.drop(['Latitude', 'Longitude'], axis = 1)

In [ ]:
# prompt: df to pkl download

from google.colab import files

# Convert the DataFrame to a pickle object
X_Dataset2.to_pickle('X_Dataset2.pkl')

# Download the pickle file
files.download('X_Dataset2.pkl')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
accidentdata = accidentdata.drop(['age'], axis = 1)

In [ ]:
X2

In [ ]:
X.Accident_Location.value_counts()

Accident_Location
Rural Areas            73158
City/Town              34930
Villages settlement     6027
Name: count, dtype: int64

In [ ]:
X.columns

Index(['DISTRICTNAME', 'UNITNAME', 'Year', 'Accident_Spot',
       'Accident_Location', 'Accident_SubLocation', 'Hit_Run',
       'Collision_Type', 'Junction_Control', 'Road_Character', 'Road_Type',
       'Surface_Type', 'Surface_Condition', 'Road_Condition', 'Weather',
       'Accident_Road', 'Latitude', 'Longitude', 'Month', 'age', 'Sex',
       'PersonType', 'Vehicle_Involvement', 'severity_score'],
      dtype='object')

In [ ]:
accidentdata.Road_Character.value_counts()

Road_Character
Straight and flat    277190
Curve                160756
Crest of hill         19532
Incline               18937
Curve and Incline      8856
Dip or trough          2563
Name: count, dtype: int64

In [ ]:
accidentdata.loc[accidentdata['Road_Character'] == 'Hump', 'Road_Character'] = 'Crest of hill'


In [ ]:
# prompt: print seperate value counts for all columns of X

for col in accidentdata.columns:
  print(accidentdata[col].value_counts())
  print()


In [ ]:
import numpy as np
import pandas as pd

# Loop through each column in the DataFrame
for column in accidentdata.columns:
    # Check if NaN exists in the column
    if accidentdata[column].isna().any():
        # Get the count of NaN occurrences
        na_count = accidentdata[column].isna().sum()

        # Calculate the total count of other values (excluding NaN)
        total_count = accidentdata[column].notna().sum()

        # Calculate the distribution ratio for other values
        distribution_ratio = accidentdata[column].value_counts(dropna=True) / total_count

        # Update NaN values with other options based on their count
        other_options = distribution_ratio.index
        weights = distribution_ratio.values
        new_values = pd.Series(np.random.choice(other_options, size=na_count, p=weights), index=accidentdata[accidentdata[column].isna()].index)
        accidentdata.loc[new_values.index, column] = new_values


In [ ]:
import pandas as pd
# Load the pickle object
accidentdata = pd.read_pickle('accidentdata.pkl')


In [ ]:
import re

for unit in accidentdata['UNITNAME'].unique():
    unit2 = re.sub(r'\W+', '_', unit)
    exec(f"{unit2} = accidentdata[accidentdata['UNITNAME'] == '{unit}'].copy()")
    exec(f"{unit2} = {unit2}.drop(['DISTRICTNAME','UNITNAME', 'Severity', 'Road_Character', 'Year'], axis=1)")

In [ ]:
for district in accidentdata['DISTRICTNAME'].unique():
    district2 = re.sub(r'\W+', '_', district)
    exec(f"{district2} = accidentdata[accidentdata['DISTRICTNAME'] == '{district}'].copy()")
    exec(f"{district2} = {district2}.drop(['DISTRICTNAME','UNITNAME', 'Severity', 'Road_Character', 'Year'], axis=1)")

In [ ]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import numpy as np
from sklearn.metrics import silhouette_score

def get_clusters(unit_or_dist_name):

  le_Accident_Spot = LabelEncoder()
  unit_or_dist_name['Accident_Spot'] = le_Accident_Spot.fit_transform(unit_or_dist_name['Accident_Spot'])

  le_Accident_SubLocation = LabelEncoder()
  unit_or_dist_name['Accident_SubLocation'] = le_Accident_SubLocation.fit_transform(unit_or_dist_name['Accident_SubLocation'])

  le_Road_Type = LabelEncoder()
  unit_or_dist_name['Road_Type'] = le_Road_Type.fit_transform(unit_or_dist_name['Road_Type'])

  scaler = StandardScaler()
  X_scaled = scaler.fit_transform(unit_or_dist_name)

  pca = PCA(n_components=2)
  pca_scaled = pca.fit_transform(X_scaled)

  k_max = 0
  silhouette_max = 0
  for k in range(2, 8):
    kmeans = KMeans(n_clusters=k, random_state=0, n_init="auto").fit(unit_or_dist_name)
    clusters = kmeans.labels_
    silhouette_avg = silhouette_score(unit_or_dist_name, clusters)
    if(silhouette_avg > silhouette_max):
      silhouette_max = silhouette_avg
      k_max = k

  kmeans = KMeans(n_clusters=4, random_state=0, n_init="auto").fit(unit_or_dist_name)
  clusters = kmeans.labels_

  pca_transformed_data = pca.transform(X_scaled)
  cluster_labels = clusters

  cluster_centroids_pca = []
  cluster_centroids_original = []
  cluster_centroids_unscaled = []

  for label in np.unique(cluster_labels):
      cluster_points = pca_transformed_data[cluster_labels == label]
      cluster_centroid = np.mean(cluster_points, axis=0)
      cluster_centroids_pca.append(cluster_centroid)

      cluster_centroid_original = pca.inverse_transform(cluster_centroid.reshape(1, -1))
      cluster_centroids_original.append(cluster_centroid_original[0])

      cluster_centroid_unscaled = scaler.inverse_transform(cluster_centroid_original.reshape(1, -1))
      cluster_centroids_unscaled.append(cluster_centroid_unscaled[0])

      encoders = [le_Accident_Spot, le_Accident_SubLocation, le_Road_Type]

      decoded_data = []
      for encoded_values in cluster_centroids_unscaled:
          decoded_values = []
          decoded_values.append(int(np.round(encoded_values[0])))
          for i, encoder in enumerate(encoders):
                val = int(np.floor(encoded_values[i+1]))
                decoded = encoder.inverse_transform([val])
                decoded_values.append(decoded[0])
          decoded_data.append(decoded_values)
  return decoded_data, cluster_centroids_unscaled, encoders, scaler

In [ ]:
decoded_data, cluster_centroids_unscaled, encoders, scaler = get_clusters(Bagalkot)
decoded_data2 = decoded_data
print(decoded_data)
print(decoded_data[0][0])

[[3, 'Narrow road', 'Near Hospital', 'Forest Road'], [8, 'Railway crossing', 'Near a recreation place/cinema', 'Feeder Road'], [8, 'Offset', 'Near a religious place', 'One way'], [5, 'More than four arms', 'Near a factory industrial area', 'One way']]
3


In [ ]:
new_data = pd.DataFrame({'Month': [8],
                         'Accident_Spot': ['Narrow road'],
                         'Accident_SubLocation': ['Near Hospital'],
                         'Road_Type': ['Forest Road']})
import math
def eucledian(a, b):
  return math.sqrt(sum((x-y)**2 for x, y in zip(a, b)))

def fit_in_cluster(unit_or_dist_name, new_data):
  decoded_data, cluster_centroids_unscaled, encoders, scaler = get_clusters(unit_or_dist_name)
  min_eucledian = np.inf
  indx = -1
  i = 0
  new_data['Accident_Spot'] = encoders[0].fit_transform(new_data['Accident_Spot'])
  new_data['Accident_SubLocation'] = encoders[1].fit_transform(new_data['Accident_SubLocation'])
  new_data['Road_Type'] = encoders[2].fit_transform(new_data['Road_Type'])

  for cluster in cluster_centroids_unscaled:
    print(cluster)
    euc_dist = eucledian(new_data.iloc[0].to_numpy(), cluster)
    min_eucledian = max(euc_dist, min_eucledian)
    if(min_eucledian == euc_dist):
      indx = i
    i+=1
  return decoded_data2[indx]

In [ ]:
ans = fit_in_cluster(Bagalkot, new_data)

[3.3763403  9.28093724 5.39497023 4.6318403 ]
[ 7.95281841 12.92728982  9.17231259  3.45949951]
[ 7.95920028 10.78877312 10.32852541  8.61164625]
[5.3449803  8.84787731 8.09454786 8.93989536]


In [ ]:
ans